---
- name: system config for rpi-timelapse
  hosts: localhost
  connection: local
  gather_facts: false
  become_user: root
  become: yes

  tasks:
    - name: install packages for camera
      ansible.builtin.apt:
        pkg:
          - python3-picamera2
          - python3-apscheduler

